### ISSUE TITLE
Unable to run tpm2_unseal

### ISSUE THREAD

**Issue by JulianGodd** [kishorv06/arch-mkinitcpio-clevis-hook#3]
```
I 0.1043131 x86/cpu: SGX disabled by BIOS.
:: running early hook [udev] Starting systemd-udeud version 253.1-3-arch
:: running hook [udev]
:: Triggering uevents... :: running hook [keymap]
:: Loading keymap...done. :: running hook [clevis]

Attempting to unlock /dev/nume0n1p2 with TPM...
WARNING:esys:src/tss2-esys/api/Esys_Unseal.c:295: Esys_Unseal_Finish() Received TPM Error ERROR:esys:src/tss2-esys/api/Esys_Unseal.c:98: Esys_Unseal() Esys Finish ErrorCode (0x0000099d)
ERROR: Esys_Unseal (0x99D) - tpm:session(1):a policy check failed
ERROR: Unable to run tpm2_unseal Unsealing jwk from TPM failed!
WARNING:esys:src/tss2-esys/api/Esys_Unseal.c:295: Esys_Unseal_Finish() Received
TPM Error
ERROR:esys:src/tss2-esys/api/Esys_Unseal.c:98: Esys_Unseal() Esys Finish ErrorCode (0x0000099d)
ERROR: Esys_Unseal (0x99D) - tpm:session(1): a policy check failed ERROR: Unable to run tpm2_unseal
Unsealing jwk from TPM failed! /dev/nume0n1p2 could not be opened.
ERROR: TPM unlock failed. :: running hook [encrypt]

A password is required to access the luksdev volume: Enter passphrase for /dev/nume0n1p2:
```

I ran the setup instructions for the AUR version and get this error upon restart. 

At one point I was able to unlock the tpm with the second of two (seemingly identical) clevis keys but after changing some bios settings I wasn't able to get it to work again. (I'm pretty certain I reset everything to the way it was before)

I've also made multiple attempts using the new systemd unlocking like suggested at the top of the repo. As I was unable to recover back to the os after it failed to unlock the drive, I had to fully reinstall the os for each attempt making me return to this project.

I also tested using a sha256 key for clevis instead in case this could affect it. 

I saw elsewhere that clearing the tpm could fix this but calling `tpm2_clear` didn't fix my issue.

Between attempts with different tools or where forced I reinstalled from scratch with archinstall

I'm happy to try whatever suggestions you have.

Thanks in advance for any help. This is the last thing I need to setup before I feel like I can make arch my home

**Comment by kishorv06** [comment]
Hey @JulianGodd, This project is more like a wrapper around clevis. The error you have posted seems to be related to clevis. Also if possible, I would recommend using systemd instead of clevis. It is much faster and easier to setup.

This is how I configured mine.
```
/etc/mkinitcpio.conf

MODULES=(tpm_tis)
HOOKS="base systemd autodetect modconf block keyboard sd-vconsole sd-encrypt lvm2 filesystems fsck"

/etc/sdboot-manage.conf

LINUX_OPTIONS="rd.luks.options=tpm2-device=auto"
LINUX_FALLBACK_OPTIONS="rd.luks.options=tpm2-device=auto"
```

**Comment by JulianGodd** [comment]
Hey, thanks for the response. I ended up getting it working with systemd and booster after some tinkering.
I'm guessing adding the LINUX_OPTIONS and LINUX_FALLBACK_OPTIONS flags could have been the fix as I didn't have these. I was brand new to systemd-boot conf files when I started on this. 

I'll definitely refer back to your response if I'm messing with this again.

Thanks again for the help
