### ISSUE TITLE
tpm2_flushcontent: command not found error when trying to unlock

### ISSUE THREAD

**Issue by SimPilotAdamT** [kishorv06/arch-mkinitcpio-clevis-hook#4]
Basically the title, got photos of the error with increasing Linux loglevels, 3, 5, 6, and 7.

![PXL_20230723_220318739](https://github.com/kishorv06/arch-mkinitcpio-clevis-hook/assets/71192298/e9a2b44e-8218-49ab-93ee-0146c09859b8)
![PXL_20230723_220436547](https://github.com/kishorv06/arch-mkinitcpio-clevis-hook/assets/71192298/58c21b60-3a75-493d-9d77-6181f4992d03)
![PXL_20230723_220627932](https://github.com/kishorv06/arch-mkinitcpio-clevis-hook/assets/71192298/e6e73e5d-d4d1-486c-9c74-75d6d9bc82c3)
![PXL_20230723_220742782](https://github.com/kishorv06/arch-mkinitcpio-clevis-hook/assets/71192298/66a2f1de-1345-4f36-a8e5-70edd4ad6e39)

**Comment by vitberget** [comment]
I managed to fix it with adding the line `add_binary "tpm2_flushcontext"` in `/etc/initcpio/install/clevis`. (And then ran `sudo mkinitcpio -P`).

**Comment by SimPilotAdamT** [comment]
> I managed to fix it with adding the line `add_binary "tpm2_flushcontext"` in `/etc/initcpio/install/clevis`. (And then ran `sudo mkinitcpio -P`).

Thanks much, I opened #5 to get that merged here. In the meantime we wait, or use my fork which has the change implemented... https://github.com/kishorv06/arch-mkinitcpio-clevis-hook/issues/4#issuecomment-1650309682

The AUR packaage is set to continue tracking this one's main branch, for now. I might switch that to my fork depending on the pr.
