### ISSUE TITLE
Clevis not automatically decrypting LUKS with Artix, s6 init and Grub

### ISSUE THREAD

**Issue by Lazerbeak12345** [kishorv06/arch-mkinitcpio-clevis-hook#7]
Here's what actually happens

| \               | GRUB Decryption ON                                                 | Grub Decryption OFF                  |
|-----------------|--------------------------------------------------------------------|--------------------------------------|
| Clevis Hook ON  | Grub prompts for Password before Grub Boot menu (before initramfs) | Takes me to initramfs recovery shell. Had to call cryptsetup and chroot manually |
| Clevis Hook OFF | Grub prompts for Password before Grub Boot menu (before initramfs) | Haven't dared to try                 |

What I expect to happen is

| \               | GRUB Decryption ON                                                 | Grub Decryption OFF                                      |
|-----------------|--------------------------------------------------------------------|----------------------------------------------------------|
| Clevis Hook ON  | Grub prompts for Password before Grub Boot menu (before initramfs) | Clevis Decrypts without password prompt during initramfs |
| Clevis Hook OFF | Grub prompts for Password before Grub Boot menu (before initramfs) | N/A                                                      |

## What do you mean "Grub decryption?"

The GRUB encryption I'm talking about is to set (root partition UUID replaced with `<uuid here>` for my privacy):

>`/etc/default/grub`
>```
>GRUB_CMDLINE_LINUX_DEFAULT='quiet cryptdevice=UUID=<uuid here>:luks-<uuid here> root=/dev/mapper/luks-<uuid here> acpi_osi="!Windows 2020"'
>```

For whatever reason, this causes grub to prompt for the LUKS decryption password _before the selection screen_. Since the disk is decrypted by the time the clevis hook is called, this message is printed:

https://github.com/kishorviswanathan/arch-mkinitcpio-clevis-hook/blob/744ff23072651d3b9250383ab070d36e70c52679/hooks/clevis#L15

### Clevis enabled

```
HOOKS="base udev autodetect modconf block keyboard keymap consolefont clevis encrypt filesystems fsck"
```

### Clevis disabled

```
HOOKS="base udev autodetect modconf block keyboard keymap consolefont encrypt filesystems fsck"
```

**Comment by kishorviswanathan** [comment]
Hi @Lazerbeak12345 

I don't personally use this hook anymore as `systemd` added support for LUKS decryption with TPM. So I don't have a way to test, but I will try to help you as much as possible.

From what you are describing, it looks like your `initramfs/kernel` is also inside an encrypted partition. In that case, you cannot disable GRUB decryption. GRUB will have to unlock the partition which has `initramfs` and `kernel`. Only then it can load `clevis`, which can decrypt any remaining partitions.

If you want a passwordless decryption setup, you should keep your `kernel` partition unencrypted. Then GRUB can access it without a password, load `clevis`, which then decrypts your `/` with TPM.

For example, refer the [Arch wiki](https://wiki.archlinux.org/title/Dm-crypt/Encrypting_an_entire_system#LUKS_on_a_partition_with_TPM2_and_Secure_Boot). Here `systemd-boot` keeps kernel in the `/efi` partition, which is not encrypted.

**Comment by Lazerbeak12345** [comment]
Thanks for the quick response.

I did a bit more digging and determined that my kernel _isnt_ encrypted, but for whatever reason the graphical Artix installer was configured this way.

The real bug I'm reporting is that with grub disabled and this hook enabled, it:

- loads the kernel
- loads the initramfs
- then fails to decrypt the root.

Unfortunately, I don't have a way to experiment with my old setup either, since I've now migrated my root partition into a new LUKS inside of an LVM. (The graphical installer didn't give me a swap). I haven't yet tried this hook on the "new" system. I expect very different results, but don't know yet. (Since I'm seeing a password prompt during initramfs instead of it kicking me to recovery mode)

PS: I'm totally gonna report both of those misconfigurations to the Artix Calamaris project. I think we both would like them fixed lol.

**Comment by kishorviswanathan** [comment]
I have never used GRUB with encrypted partitions before, but if GRUB asks for a password before showing the boot menu, probably your boot partition is encrypted. It is only after selecting the boot entry, kernel and initramfs are loaded.

If for some reason clevis fails to decrypt, it should fallback to the password prompt. In a normal setup, you will not end up in a recovery shell. Probably something else is broken here. Are you sure it is the initramfs shell and not GRUB recovery shell ? To understand that I would need more information, probably your logs when booting.

Also if that is not the case, depending on which PCRs you have enrolled while setting up clevis, you might have to login with a password and re-enroll again. This is the case, if you are using PCRs monitoring `cmdline` arguments or kernel checksums.

**Comment by kishorviswanathan** [comment]
Just saw your updated comment. Try adding the hook and If you are seeing a password prompt just once, then we are good. `clevis` is unable to decrypt the partition, but the next hook in the list `encrypt` is able to do it.

Now to debug why `celvis` was unable to decrypt, you should look into the PCRs used. If it includes something that monitors boot arguments, kernel or initramfs, re-enroll after booting with a password. `celvis` should be able to decrypt the disk starting next boot until something changes again in PCR.

Please test and report back.

**Comment by Lazerbeak12345** [comment]
I didn't get the chance to test with that hook yet, but would like to correct an error.

I figured out why the `crypto` mkinitramfs hook fails:

My process for disabling grub's deception was wrong. I do know that grub looks at the kernel hooks, and assumed that was how it did it, but as a side effect of (incorrectly) disabling grub this way, the kernel did not get the args to be able to decrypt it. I know this is the case, because now that my root partition is different, grub displays the odd behavior of

- Asking for the decryption key for the old Root partition (which is still present - I've kept it for the sole purpose of debugging this issue)
- then, after grub decrypts, the crypto hook triggers, fails (for unrelated issues) then asks for a password (which is a success.

This leads me to believe that I'll also have to re-test everything in the "Grub encryption disabled" column of the tables above. (Side note - preliminary attempts to change the `GRUB_ENABLE_CRYPTODISK` away from `y` have failed - I'll have to do more research to be able to do this correctly.)

**Comment by kishorviswanathan** [comment]
Okay, Clevis only handles the part after GRUB loads the kernel. Celvis will be able to decrypt only if the system configuration is the same as when you did `luks bind`. Since you are playing with kernel args, GRUB and hooks, it will keep on changing. To test if there is something wrong with this hook, I would recommend the following steps:

1. Configure everything as mentioned in the readme.
2. Reboot once, clevis would fail to decrypt. Continue with the password.
3. Once booted, bind the TPM again. Do not change anything else.
4. Try rebooting once. Clevis should decrypt now.

**Comment by Lazerbeak12345** [comment]
After further digging, it seems that contrary to what I believed - my initramfs was _not_ on a decrypted partition. Either way, I can't be 100% sure - since all I have to work off of is a backup of that system - since I (effectively) re-installed my system to solve a _different_ problem.

Thanks for your patience. At some point I might try to recreate this with a virtual machine - but I'm not making any promises at even attempting it.
